version: 0.2 # This is the reference from the devloper/DevOps Engineer

phases:
  install:
    runtime-versions:
      nodejs: 22 # Set this to the Node.js version you need
    commands:
      - echo Installing Node.js in the install phase
      - npm install # To install NPM
build:
      - echo Building the application...
      - npm run build
      - pwd    
  post_build:
    commands:
      - echo The build is complete
artifacts:
  files:
    - 'build/**/*'
